namespace MyAIRunningMate.Contracts.Analytics.Responses;

public record WeeklyInsightsResponse(
    double RunningTimeSeconds,
    double RunningMovingTimeSeconds,
    double RunningDistanceMetres,
    double SwimmingTimeSeconds,
    double SwimmingDistanceMetres,
    int TotalCaloriesBurned,
    double TotalTrainingScore,
    double TrainingConsistencyScore,
    int MorningActivities,
    int AfternoonActivities,
    int EveningActivities,
    int NightActivities,
    IEnumerable<string> Locations,
    int RestDays,
    double RunningMovingEfficiency,
    double PausedSeconds,
    double BodyBatteryDepletion,
    double BodyBatteryEfficiency,
    double RecoveryTimeGenerated,
    double HeartRateIntensityScore,
    double VolumetricOxygenMaxTrend,
    double VolumetricOxygenMaxDiffPercent,
    double RunningEconomyIndex);