FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install Firebase Admin SDK and other necessary Python packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt firebase-admin

# Copy the rest of the code
COPY . ./

# Set environment variables (Kafka broker and topic)
ENV KAFKA_BROKER=kafka:9092
ENV ACTIVITY_TOPIC=activities_topic
ENV INSIGHTS_TOPIC=insights_topic

# Command to start the consumer
CMD ["python", "main.py"]