services:
  garmin_sync:
    build: ./garmin_ingestion_service
    container_name: garmin_ingestion_service
    restart: always
    env_file:
      - ./garmin_ingestion_service/.env
    volumes:
      - ../../data/garmin_activities:/app/data/garmin_activities

volumes:
  garmin_data: