export const DEFAULT_WEEKLY_INSIGHTS = {
  running_distance_metres: 0,
  running_time_seconds: 0,
  running_moving_time_seconds: 0,
  swimming_distance_metres: 0,
  swimming_time_seconds: 0,
  morning_activities: 0,
  afternoon_activities: 0,
  evening_activities: 0,
  night_activities: 0,
  total_running_elevation_gain: 0,
  mean_average_heart_rate: 0,
  mean_max_heart_rate: 0,
  mean_training_effect: 0,
  total_training_effect: 0,
  total_calories_burned: 0,
  running_time_break_seconds: 0,
  running_moving_efficiency: 0,
  caloric_intensity: 0,
  elevation_intensity: 0,
  rest_days: 0,
  locations: [],
  training_consistency_score: 0,
};